### ISSUE TITLE
Transmog item atlas?

### ISSUE THREAD

**Issue by Nikoichu** [Otari98/Tmog#1]
This is a great addon, but it would be so much more useful if it had an atlas to browse all item appearances, similar to the MogIt addon for Ascension. It would help transmog nerds so much.

Basically it should have an UI, which lists all available item appearances in the game with previews; hovering over one lists all items that have that appearance (and possibly their sources?). Shift-clicking previews it in the dressing room UI, so you can construct transmog sets ingame. It should also let you filter by collected/not collected; type (weapon, armor), subtype (1h Axe, Staff, Wand, Cloth, Helm etc.), Faction (Horde/alliance), Class (For tier sets and class quest rewards), level, rarity, source, name, etc.

I know it's a lot of work, but it would be a godsent for all transmoggers.

**Comment by Otari98** [comment]
Thats asking alot

**Comment by Nikoichu** [comment]
I know. Let a man dream. 😄

**Comment by Otari98** [comment]
Its done mate, get the new version

**Comment by Nikoichu** [comment]
Thank you so much! This is perfect, EXACTLY what I had in mind! You are my personal hero!

EDIT: To celebrate, I created quite a few transmog sets using your addon, check them out: https://forum.turtle-wow.org/viewtopic.php?p=108042#p108042
Thanks again, I am having a blast! <3
If you have any personal requests for transmog sets you want me to make for you, don't hesitate to ask, it's the least I could do :)
