### ISSUE TITLE
pfUI minimap addon frame

### ISSUE THREAD

**Issue by Rahnd2137** [Otari98/Tmog#2]
Hey!
pfUI minimap addon frame isn't "catching" the Tmog button.

**Comment by Otari98** [comment]
I dont use pfUI.
Looking at the pfUi's code i cant see why it wouldn't catch it...

**Comment by Rahnd2137** [comment]
Here is a solution for that problem from one and only Shagu! :D 
https://github.com/shagu/pfUI/issues/1372
