### ISSUE TITLE
Paladin staffs (and held in off-hand)

### ISSUE THREAD

**Issue by Eirosdev** [Otari98/Tmog#3]
```lua
--Tmog.lua, line 70
local tmog_paladin = {
    ["Cloth"]=true,
    ["Leather"]=true,
    ["Mail"]=true,
    ["Plate"]=true,
    --["Staff"]=true, #i wish they could
    ["Mace"]=true,
    ["Sword"]=true,
    ["Axe"]=true,
    ["Polearm"]=true,
    ["Shield"]=true
}
``` 
Also, the variables for each class are missing "Held In Off-hand"

Thank you for your great addon!

**Comment by Otari98** [comment]
paladins cant use staves, every class can use Held in Off-hand items, so what is the issue here?

**Comment by Eirosdev** [comment]
Tmog.lua, line 75 states that paladins is able to use stavess. This is wrong, and leads to the tooltip saying "not collected" for staves.
The other note about off-hands is not really an issue, since the tooltip displays correctly if off hands are collected or not.

**Comment by Otari98** [comment]
Right

**Comment by Otari98** [comment]
Fixed
